# Generated by Django 3.2.7 on 2021-11-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aadhardb',
            fields=[
                ('aadharnumber', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('aadharname', models.CharField(max_length=100)),
                ('aadharbirth', models.CharField(max_length=100)),
                ('aadhargender', models.CharField(max_length=100)),
                ('aadharimage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='dirverdata',
            fields=[
                ('drlicenceno', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('drlicencename', models.CharField(max_length=100)),
                ('drlicencelname', models.CharField(max_length=100)),
                ('drlicenceimage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('select_bank', models.CharField(choices=[('SBI', 'State Bank Of India'), ('Alla', 'Allahabad Bank'), ('Yes', 'Yes Bank')], default='green', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='voteriddata',
            fields=[
                ('voterfname', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('votername', models.CharField(max_length=100)),
            ],
        ),
    ]
