# Generated by Django 3.2.7 on 2021-11-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='panddata',
            fields=[
                ('panno', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fathername', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
