# Generated by Django 3.2.7 on 2021-11-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcard', '0002_panddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='panddata',
            name='panimage',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
