# Generated by Django 3.2.7 on 2021-11-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcard', '0003_panddata_panimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteriddata',
            name='voterimage',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
