# Generated by Django 3.2.7 on 2021-11-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcard', '0004_voteriddata_voterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='panddata',
            name='pandob',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
