# Generated by Django 3.2.7 on 2021-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcard', '0005_panddata_pandob'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteriddata',
            name='voterid',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
