# Generated by Django 3.2.7 on 2021-11-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcard', '0006_voteriddata_voterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhardb',
            name='aadharno',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
