# Generated by Django 3.2.7 on 2021-11-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcard', '0007_aadhardb_aadharno'),
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panid', models.CharField(max_length=100, unique=True)),
                ('aadharid', models.CharField(max_length=100, unique=True)),
                ('drivingid', models.CharField(max_length=100, unique=True)),
                ('voterid', models.CharField(max_length=100, unique=True)),
                ('pname', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
