# Generated by Django 3.2.7 on 2021-11-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcard', '0008_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='aadharid',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='api',
            name='drivingid',
        ),
        migrations.RemoveField(
            model_name='api',
            name='panid',
        ),
        migrations.RemoveField(
            model_name='api',
            name='voterid',
        ),
    ]
